### ISSUE TITLE
Kafka output plugin and distributed architecture

### ISSUE THREAD

**Issue by vi9dgupta** [CESNET/ipfixcol2#1]
1. If kafka with json output plugin supported?
2. Distributed architecture supported?
3.Could addition of ODID along with other information in json be done?
Regards

**Comment by Lukas955** [comment]
Hi,

first of all, thank you for your interest in IPFIXcol2! Right now, all these feature you mentioned are not available yet. IPFIXcol2 is basically a new generation of the original IPFIXcol and all plugins must be adapted to the new API. This first release supports only essential plugins (JSON - without kafka, UniRec, etc.). Moreover, during the next few months we would like to focus on key parts of the collector core (support for NetFlow v5/v9, which implementation is currently work in progress).

However, I expect that all features you asked for will be available during the first quarter of 2019. Are there any other plugins that you are actively using or you are interested in?

Lukáš
