### ISSUE TITLE
Migration from ipfixcol to ipfixcol2 

### ISSUE THREAD

**Issue by neotheonce** [CESNET/ipfixcol2#102]
We are using ipfixcol on CentOS7 now migrating to ipfixcol2 version.  We have built it on Ubuntu 22

Following is current ipfixcol (old version) startup.xml

`<?xml version="1.0" encoding="UTF-8"?>
<ipfix xmlns="urn:ietf:params:xml:ns:yang:ietf-ipfix-psamp">

        
        <collectingProcess>
                
                <name>UDP collector</name>
                
                <udpCollector>
                        
                        <name>Listening port 2055</name>
                        
                        <localPort>2055</localPort>
                        
                        <templateLifeTime>1800</templateLifeTime>
                        
                        <optionsTemplateLifeTime>1800</optionsTemplateLifeTime>
                        
                        
                        
                        
                        
                        <localIPAddress>172.16.101.215</localIPAddress>
                </udpCollector>
                
                <exportingProcess>File writer UDP</exportingProcess>
                
                <statisticsFile>/tmp/ipfixcol_stat.log</statisticsFile>
        </collectingProcess>

        
        <exportingProcess>
                
                <name>File writer UDP</name>
                <destination>
                        <name>Write to /tmp folder</name>
                        <fileWriter>
                                <fileFormat>kafka</fileFormat>
                                <ignoreUnknown>false</ignoreUnknown>
                                
                                <nonPrintableChar>no</nonPrintableChar>
                                <bootstrapServers>kafka-1:6667,kafka-2:6667,kafka-3:6667</bootstrapServers>
                                <topic>ipfix-other</topic>
                                <useAvro>false</useAvro>
                                <numThreads>8</numThreads>
                                <useDeliveryCallback>no</useDeliveryCallback>
                                
                                <ignoredFieldNames>fid,tcpCB,sourceASN,destASN,nextHop,flowSmplr</ignoredFieldNames>
                                <topics>
                                   <topic><name>ipfix</name><field id="16"/></topic>
                                   <topic><name>ipfix</name><field enterprise="9" id="12236"/></topic>
                                   <topic><name>ipfix</name><field enterprise="9" id="4246"/></topic>
                                   <topic><name>ipfix</name><field enterprise="4294967295" id="4331"/></topic>
                                </topics>
                                <compression>none</compression>
                        </fileWriter>
                </destination>
                <singleManager>yes</singleManager>
        </exportingProcess>
</ipfix>
`
I need help in creating equivalent ipfixcol2 startup.xml. I gone through ipfixcol2 and kafka documentations but could not find any pointer to get above working with new collector.

--
Thanks,
P

**Comment by Lukas955** [comment]
Hi,

all you need to do is to combine [UDP plugin](https://github.com/CESNET/ipfixcol2/tree/master/src/plugins/input/udp) and [JSON plugin](https://github.com/CESNET/ipfixcol2/tree/master/src/plugins/output/json). Example configuration file is available [here](https://github.com/CESNET/ipfixcol2/blob/master/doc/data/configs/udp2json.xml).

In you case, basic configuration should look like this (not tested):
``` xml
<ipfixcol2>
  <!-- Input plugins -->
  <inputPlugins>
    <input>
      <name>UDP collector</name>
      <plugin>udp</plugin>
      <params>
        <localPort>2055</localPort>
        <templateLifeTime>1800</templateLifeTime>
        <optionsTemplateLifeTime>1800</optionsTemplateLifeTime>
        <localIPAddress>172.16.101.215</localIPAddress>
      </params>
    </input>
  </inputPlugins>

  <!-- Output plugins -->
  <outputPlugins>
    <output>
      <name>JSON output</name>
      <plugin>json</plugin>
      <params>
        <ignoreUnknown>false</ignoreUnknown>
        <nonPrintableChar>false</nonPrintableChar>
        <!-- see JSON plugin documentation for additional formating parameters -->

        <outputs>
          <kafka>
            <name>Send to Kafka</name>
            <brokers>kafka-1:6667,kafka-2:6667,kafka-3:6667</brokers>
            <topic>ipfix-other</topic>
            <blocking>false</blocking>
            <partition>unassigned</partition>

            <!-- Zero or more additional librdkafka properties -->
            <!--
            <property>
              <key>compression.codec</key>
              <value>lz4</value>
            </property>
            -->
          </kafka>        
        </outputs>
      </params>
    </output>
  </outputPlugins>
</ipfixcol2>
```

However, I noticed that you configuration contains additional parameters (e.g. ignoredFieldNames, useAvro, ...) that are not present in the previous plugin. You seem to be using some custom modifications.


Lukas

**Comment by neotheonce** [comment]
Hello Lukas,

Thanks for your prompt response. Leaving custom parameters aside,  I am more interested in porting below configuration in ipfixcol2. Will this work if I copy paste it as it is in side <kafka> </kafka> tags ?. OR is there any other way to use specific topic based on incoming data? 

`                            <ignoredFieldNames>fid,tcpCB,sourceASN,destASN,nextHop,flowSmplr</ignoredFieldNames>
                            <topics>
                               <topic><name>ipfix</name><field id="16"/></topic>
                               <topic><name>ipfix</name><field enterprise="9" id="12236"/></topic>
                               <topic><name>ipfix</name><field enterprise="9" id="4246"/></topic>
                               <topic><name>ipfix</name><field enterprise="4294967295" id="4331"/></topic>
                            </topics>
`

**Comment by Lukas955** [comment]
Hi,

Copy and paste will not work. These are parameters that even the original plugin (from the former ipfixcol) did not implement at all. Someone from your company probably added this functionality to their own copy of the plugin. I honestly have no idea what these parameters of yours are supposed to do.

Lukas
