### ISSUE TITLE
Instructions to decode a private enterprise's data

### ISSUE THREAD

**Issue by praneethravuri** [CESNET/ipfixcol2#103]
I have built ipfixcol2 and libfds from source. I am trying to decode the ipfix data stream coming via TCP but for some reason, only the template information (enterprise element id, enterprise id, field length) are visible but not the actual decoded message itself

What is the procedure to add another enterprise's information?

Should I make any changes in libfds like changing the `aliases.xml` and `mappings.xml` in `libfds/config/system`? Also, should I insert the enterprise's xml file in element's directory?

Thanks in advance!

**Comment by sedmicha** [comment]
That does indeed seem like you are missing some definitions of some of your IPFIX fields. All you should need to do is provide a XML file describing the fields and place it in the `/etc/libfds/user/elements/` directory.  As a reference of how the file should be structured and what it should contain, you can use one of the existing files such as `/etc/libfds/system/elements/cesnet.xml` (also available [here](https://github.com/CESNET/libfds/blob/master/config/system/elements/cesnet.xml)). Upon placing the file in that location, the collector should automatically locate it and load it on next startup, and the values of your fields should be getting decoded fully. If your issue still remains after following these steps, it would be beneficial to show your configuration and the output you're getting.

**Comment by praneethravuri** [comment]
@sedmicha thanks for your reply. Your advice is working and the decoder is able to read the enterprise data.

Thank you.
