### ISSUE TITLE
ENHANCEMENT: PEN Fields

### ISSUE THREAD

**Issue by vi9dgupta** [CESNET/ipfixcol2#18]
Can we have configuration file for PEN related fields like ipfix-elements.xml of earlier version.

**Comment by Lukas955** [comment]
Sure,
configuration files are now handled by libfds and stored usually in /etc/libfds/ or /usr/local/etc/libfds (depends on installation process). You can also use `ipfixcol2 -h` and see the description of `-e DIR` parameter for exact directory location.

Commonly provided configuration files are stored in `system` subdirectory and can be modified in the future by library updates. Therefore, there is also second subdirectory, `user`, where users can add they own configurations files that will newer be modified. The hierarchy of the subdirectories is the same.

So, if you want to add new IEs, just add one or more files to `/etc/libfds/user/elements/` (or to the directory specific for your system). Each file can contain only IEs for exactly one PEN and the structure of the file is following:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<ipfix-elements>
    <scope>
        <pen>8057</pen>                  <!-- PEN number -->
        <name>name_of_your_pen</name>    <!-- PEN Name   -->
        <biflow mode="none"></biflow>
    </scope>

    <!-- One or more IEs -->
    <element>
        <id>1</id>
        <name>DNSRCode</name>
        <dataType>unsigned8</dataType>
    </element>
</ipfix-elements>
```

If you have any PEN definitions that might be interesting for other users, I would like to distribute them together with the library.
