### ISSUE TITLE
Kafka configuration issue

### ISSUE THREAD

**Issue by vi9dgupta** [CESNET/ipfixcol2#19]
In Kafka configuration, on defining partitions , it displays error as unknown partition. When we defined partition as unassigned, it displayed no error and records to kafka were produced.

**Comment by Lukas955** [comment]
Are you using valid partition number? Did you configured your Kafka cluster to contain multiple partitions of the particular topic (by default `ipfix`)?

**Comment by vi9dgupta** [comment]
Yes I gave valid partition number and the associated topic in kafka.

**Comment by Lukas955** [comment]
I'm **unable** to replicate your issues.

My steps:
- Setup two Kafka brokers (default server configuration - only `broker.id`, `listeners` and `log.dirs` parameters have been changed).
- Create two partitions:
`bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 2 --topic ipfix`
- Check configuration of the brokers:
`bin/kafka-topics.sh --describe --bootstrap-server localhost:9092 --topic ipfix`
OUTPUT:
```
Topic: ipfix	PartitionCount: 2	ReplicationFactor: 1	Configs: segment.bytes=1073741824
	Topic: ipfix	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
	Topic: ipfix	Partition: 1	Leader: 1	Replicas: 1	Isr: 1
```
- run 2 instances of the ipfixcol2 with the following `<outputs>` configuration of the JSON plugin:
``` xml
<kafka>
  <name>Send to Kafka</name>
  <brokers>127.0.0.1</brokers>
  <topic>ipfix</topic>
  <blocking>false</blocking>
  <partition>0</partition>     <!-- the second instance of the collector uses value "1"-->
  <property>
    <key>compression.codec</key>
    <value>lz4</value>
  </property>
</kafka>
```
- replay data to both collectors using `ipfixsend2`
- result: no error, everything works as expected

---

Can you please provide:
-  output of the following command `bin/kafka-topics.sh --describe --bootstrap-server localhost:9092 --topic ipfix`
- XML configuration of the collector

**Comment by Lukas955** [comment]
Did you manage to resolve this issue? Can I close it?

**Comment by vi9dgupta** [comment]
(1)
 ./kafka-topics.sh --describe --topic test --zookeeper 192.168.144.78:2181
Topic:test	PartitionCount:40	ReplicationFactor:1	Configs:
	Topic: test	Partition: 0	Leader: 5	Replicas: 5	Isr: 5
	Topic: test	Partition: 1	Leader: 1	Replicas: 1	Isr: 1
	Topic: test	Partition: 2	Leader: 2	Replicas: 2	Isr: 2
	Topic: test	Partition: 3	Leader: 3	Replicas: 3	Isr: 3
	Topic: test	Partition: 4	Leader: 4	Replicas: 4	Isr: 4
	Topic: test	Partition: 5	Leader: 5	Replicas: 5	Isr: 5
	Topic: test	Partition: 6	Leader: 1	Replicas: 1	Isr: 1
	Topic: test	Partition: 7	Leader: 2	Replicas: 2	Isr: 2
	Topic: test	Partition: 8	Leader: 3	Replicas: 3	Isr: 3
	Topic: test	Partition: 9	Leader: 4	Replicas: 4	Isr: 4
	Topic: test	Partition: 10	Leader: 5	Replicas: 5	Isr: 5
	Topic: test	Partition: 11	Leader: 1	Replicas: 1	Isr: 1
	Topic: test	Partition: 12	Leader: 2	Replicas: 2	Isr: 2
	Topic: test	Partition: 13	Leader: 3	Replicas: 3	Isr: 3
	Topic: test	Partition: 14	Leader: 4	Replicas: 4	Isr: 4
	Topic: test	Partition: 15	Leader: 5	Replicas: 5	Isr: 5
	Topic: test	Partition: 16	Leader: 1	Replicas: 1	Isr: 1
	Topic: test	Partition: 17	Leader: 2	Replicas: 2	Isr: 2
	Topic: test	Partition: 18	Leader: 3	Replicas: 3	Isr: 3
	Topic: test	Partition: 19	Leader: 4	Replicas: 4	Isr: 4
	Topic: test	Partition: 20	Leader: 5	Replicas: 5	Isr: 5
	Topic: test	Partition: 21	Leader: 1	Replicas: 1	Isr: 1
	Topic: test	Partition: 22	Leader: 2	Replicas: 2	Isr: 2
	Topic: test	Partition: 23	Leader: 3	Replicas: 3	Isr: 3
	Topic: test	Partition: 24	Leader: 4	Replicas: 4	Isr: 4
	Topic: test	Partition: 25	Leader: 5	Replicas: 5	Isr: 5
	Topic: test	Partition: 26	Leader: 1	Replicas: 1	Isr: 1
	Topic: test	Partition: 27	Leader: 2	Replicas: 2	Isr: 2
	Topic: test	Partition: 28	Leader: 3	Replicas: 3	Isr: 3
	Topic: test	Partition: 29	Leader: 4	Replicas: 4	Isr: 4
	Topic: test	Partition: 30	Leader: 5	Replicas: 5	Isr: 5
	Topic: test	Partition: 31	Leader: 1	Replicas: 1	Isr: 1
	Topic: test	Partition: 32	Leader: 2	Replicas: 2	Isr: 2
	Topic: test	Partition: 33	Leader: 3	Replicas: 3	Isr: 3
	Topic: test	Partition: 34	Leader: 4	Replicas: 4	Isr: 4
	Topic: test	Partition: 35	Leader: 5	Replicas: 5	Isr: 5
	Topic: test	Partition: 36	Leader: 1	Replicas: 1	Isr: 1
	Topic: test	Partition: 37	Leader: 2	Replicas: 2	Isr: 2
	Topic: test	Partition: 38	Leader: 3	Replicas: 3	Isr: 3
	Topic: test	Partition: 39	Leader: 4	Replicas: 4	Isr: 4


(2)<ipfixcol2>
    <inputPlugins>
    <input>
           <name> UDP input </name>
           <plugin> udp </plugin>
           <params>
                   <localPort>4740</localPort>
                   <localIPAddress>192.168.144.59</localIPAddress>
                   <connectionTimeout> 600 </connectionTimeout>
                   <templateLifeTime> 5400 </templateLifeTime>
                   <optionsTemplateLifeTime> 5400 </optionsTemplateLifeTime>
           </params>
    </input>
    </inputPlugins>

   <outputPlugins>
   <output>
           <name> JSON output </name>
           <plugin> json </plugin>
           <verbosity>info</verbosity>
           <params>
                   <tcpFlags> formatted </tcpFlags>
                   <timestamp> unix </timestamp>
                   <protocol> formatted </protocol>
                   <ignoreUnknown> true </ignoreUnknown>
                   <nonPrintableChar>true </nonPrintableChar>
                   <detailedInfo> true </detailedInfo>

               <outputs>
                        <kafka>
                               <name> kafka </name>
                               <brokers>192.168.144.53:9092,192.168.144.63:9092,192.168.144.73:9092,192.168.144.83:9092,192.168.144.93:9092</brokers>
                               <blocking> false </blocking>
                               <partition> unassigned </partition>
                               <topic>test1</topic>
                        </kafka>
               </outputs>
               </params>
   </output>
   </outputPlugins>
</ipfixcol2>

**Comment by Lukas955** [comment]
This configuration works, right? As you said:

> When we defined partition as unassigned, it displayed no error and records to kafka were produced.

If you see any errors, please, provide log.

**Comment by vi9dgupta** [comment]
ERROR: JSON output: rd_kafka_produce() failed: Local: Unknown partition (1x)
ERROR: JSON output: rd_kafka_produce() failed: Local: Unknown partition (12462x)
ERROR: JSON output: rd_kafka_produce() failed: Local: Unknown partition (17607x)
ERROR: JSON output: rd_kafka_produce() failed: Local: Unknown partition (17330x)
ERROR: JSON output: rd_kafka_produce() failed: Local: Unknown partition (18029x)
ERROR: JSON output: rd_kafka_produce() failed: Local: Unknown partition (17997x)
ERROR: JSON output: rd_kafka_produce() failed: Local: Unknown partition (17096x)
ERROR: JSON output: rd_kafka_produce() failed: Local: Unknown partition (17638x)
ERROR: JSON output: rd_kafka_produce() failed: Local: Unknown partition (18111x)
ERROR: JSON output: rd_kafka_produce() failed: Local: Unknown partition (17413x)

**Comment by Lukas955** [comment]
What is the value of `<partition>` parameter?

**Comment by vi9dgupta** [comment]
40

**Comment by Lukas955** [comment]
In this case, the error makes sense.
You have 40 partitions, but their indexes are 0 .. 39 (as written in your log above).

Maybe you don't understand the parameter `<property>` correctly. If the value is `unassigned`, flow records will be spread accross all partitions, however, if you specify, let's say 10, all records will be send only to partition number 10. Other partitions 0..9 and 11..39 are ignored.

**Comment by vi9dgupta** [comment]
but in ipfixcol(gen 1) as defined, it is "partitions - Number of partitions to which send data. Uses round robin to send to partitions 0 - (N-1) "

**Comment by Lukas955** [comment]
Yes, but now you are using ipfixcol2 and the partition is defined as:
`Partition number to produce to. If the value is "unassigned", then the default random distribution is used.` Please, always read the documentation first.

Is this whole issue about "round robin" distribution that you would like to use instead of the default librdkafka (random distribution)?

**Comment by Lukas955** [comment]
Closed due to inactivity.
