### ISSUE TITLE
json output : unicode nullcharacter http fields

### ISSUE THREAD

**Issue by vi9dgupta** [CESNET/ipfixcol2#22]
In Kafka Json we are getting in all http record:
"httpRequestMethod":"GET\u0000\u0000\u0000\u0000\u0000","httpRequestHost":"xml-ads.com\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","httpRequestTarget":"/in.html?q=cD0yMTkjcz00Mjc2ODMwI3Q9TUFJTlNUUkVBTSNxPTAjYz1JT\u0000\u0000\u0000\u0000"

**Comment by thorgrin** [comment]
Good for you. And what is your question?

**Comment by Lukas955** [comment]
Did the answer resolve yours issue? If so, please, close it.

**Comment by vi9dgupta** [comment]
Resolved
