### ISSUE TITLE
using json output plugin of devel branch

### ISSUE THREAD

**Issue by alireza-moradi** [CESNET/ipfixcol2#28]
hi 
i have installed ipfixcol2 devel branch for writing output stream in kafka topic , but encounter with segmentation fault error when using json plugin with every output . my os is centos 7 (also test on ubuntu 18.04)  and here is my sample conf file:

<ipfixcol2>
  
  <inputPlugins>
    <input>
      <name>UDP collector</name>
      <plugin>udp</plugin>
      <params>
        
        <localPort>5555</localPort>
        
        <localIPAddress></localIPAddress>
      </params>
    </input>
  </inputPlugins>

  
  <outputPlugins>
<output>
    <name>JSON output</name>
    <plugin>json</plugin>
    <params>
        <tcpFlags>formatted</tcpFlags>
        <timestamp>formatted</timestamp>
        <protocol>formatted</protocol>
        <ignoreUnknown>true</ignoreUnknown>
        <ignoreOptions>true</ignoreOptions>
        <nonPrintableChar>true</nonPrintableChar>
        <octetArrayAsUint>true</octetArrayAsUint>
        <numericNames>false</numericNames>
        <splitBiflow>false</splitBiflow>
        <detailedInfo>false</detailedInfo>
        <templateInfo>false</templateInfo>

        <outputs>
            
            <print>
                <name>Printer to standard output</name>
            </print>

        </outputs>
    </params>
</output>
  </outputPlugins>
</ipfixcol2>

**Comment by Lukas955** [comment]
Hi,
thank you for report, I managed to reproduce the bug. It seems that there is a problem when "<print>" output is enabled. I'll try to debug it as soon as possible and I'll let you know.

**Comment by Lukas955** [comment]
I fixed the segmentation fault caused by the printer output in `devel` branch, so it should work now.
Can you try it?

**Comment by alireza-moradi** [comment]
tnx , i will test it again and inform u ASAP

**Comment by alireza-moradi** [comment]
it works fine. 
tnx again
