### ISSUE TITLE
Enhancement: KAFKA output plugin with JSON support

### ISSUE THREAD

**Issue by vi9dgupta** [CESNET/ipfixcol2#8]
Kafka output plugin with JSON is not supported. Could you add this ?

**Comment by Lukas955** [comment]
Hello,

I think that I can implement it during the next few days. Stay tuned!

Lukas

**Comment by shiv1997narayan** [comment]
Why this plugin is not available in IPFIXcol2. As it is latest version of IPFIXcol, Where it is available.
Is any specific reason.

**Comment by Lukas955** [comment]
We wanted to reduce additional dependencies of the "base" collector as much as possible. Therefore, we created group of "extra" plugins for plugins which depend on relatively new, unstable, or uncommon libraries. For this reason, the Kafka support was removed from the JSON plugin when we were converting it under new IPFIXcol2 API.

In the following days, I will create a new "extra" Output plugin (similar to `UniRec` or `lnfstore`), which 
will be dedicated only for Kafka.

**Comment by Lukas955** [comment]
Kafka producer is now part of [JSON output plugin](https://github.com/CESNET/ipfixcol2/tree/devel/src/plugins/output/json) in `devel` branch. Please, try it and tell me if everything works as expected.

By the way, I decided not to create a new output plugin after all as the librdkafka library is now available on most systems.

**Comment by vi9dgupta** [comment]
We can't compile ipfixcol2 with kafka on ubuntu 16.
We could compile ipfixcol2 with kafka on ubuntu 18, however on running,it produces 17-20K kafka record per second though input ipfix records were much higher.
