### ISSUE TITLE
error during compiling on arch

### ISSUE THREAD

**Issue by wisperC4** [CESNET/ipfixcol2#83]
hello, 
[ 82%] Building CXX object src/tools/fdsdump/src/common/CMakeFiles/common_obj.dir/filelist.cpp.o
/tmp/ipfixcol2/src/tools/fdsdump/src/common/filelist.cpp: In member function ‘void fdsdump::FileList::add_files(const std::string&)’:
/tmp/ipfixcol2/src/tools/fdsdump/src/common/filelist.cpp:68:20: error: ‘runtime_error’ is not a member of ‘std’
   68 |         throw std::runtime_error("glob() failed: GLOB_ABORTED");
      |                    ^~~~~~~~~~~~~
/tmp/ipfixcol2/src/tools/fdsdump/src/common/filelist.cpp:46:1: note: ‘std::runtime_error’ is defined in header ‘<stdexcept>’; did you forget to ‘#include <stdexcept>’?
   45 | #include "filelist.hpp"
  +++ |+#include <stdexcept>
   46 | 
/tmp/ipfixcol2/src/tools/fdsdump/src/common/filelist.cpp:70:20: error: ‘runtime_error’ is not a member of ‘std’
   70 |         throw std::runtime_error("glob() failed: " + std::to_string(ret));
      |                    ^~~~~~~~~~~~~
/tmp/ipfixcol2/src/tools/fdsdump/src/common/filelist.cpp:70:20: note: ‘std::runtime_error’ is defined in header ‘<stdexcept>’; did you forget to ‘#include <stdexcept>’?
make[2]: *** [src/tools/fdsdump/src/common/CMakeFiles/common_obj.dir/build.make:118: src/tools/fdsdump/src/common/CMakeFiles/common_obj.dir/filelist.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1104: src/tools/fdsdump/src/common/CMakeFiles/common_obj.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by Lukas955** [comment]
Hi,
Can you tell me what operating system and what version of it you are using?

Lukas

**Comment by wisperC4** [comment]
Linux ouis 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14
+0000 x86_64 GNU/Linux
EndavourOs ( Arch base ) system up to date

git clone from master for ipfixcol2
Regards


Le mer. 30 août 2023 à 14:16, Lukáš Huták ***@***.***> a
écrit :
