### ISSUE TITLE
Support hosts by name in json output params

### ISSUE THREAD

**Issue by guru-florida** [CESNET/ipfixcol2#91]
## Problem
ipfixcol2 doesn't support hostnames for the Json output plugin, only IP addresses. I manually fixed this by short circuiting the `check_ip` function to true in the `/src/plugins/output/json/Config.cpp` file. The Sender.cpp code uses the getaddrinfo() function which supports hostnames and IP addresses, so no other code changes but to _not_ call check_ip() are needed to support this.  This may be by design, but is there a particular reason why you would _not_ want to allow hostnames? 

## Justification
I built a docker image of ipfixcol2 and docker inter-container networking relies on hostnames where the ip address is not known for configuration.

**Comment by sedmicha** [comment]
I have looked through the plugin code and there is really no reason for that check to be there, the limitation is therefore more of a bug rather than being intended. The issue has been fixed and should appear here as soon as some of our internal processes go through.

**Comment by sedmicha** [comment]
We have made a new release (v2.5.0) today that solves this issue

**Comment by guru-florida** [comment]
Thank you!
